/**
 * Z PL/SQL Analyzer
 * Copyright (C) 2015-2026 Felipe Zorzo
 * mailto:felipe AT felipezorzo DOT com DOT br
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.felipebz.zpa.api.ddl

import com.felipebz.flr.tests.Assertions.assertThat
import com.felipebz.zpa.api.DdlGrammar
import com.felipebz.zpa.api.PlSqlGrammar
import com.felipebz.zpa.api.RuleTest
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.assertj.core.api.Assertions.assertThat as assertAst

class CreateTableAsSelectTest : RuleTest() {
    @BeforeEach
    fun init() {
        setRootRule(DdlGrammar.CREATE_TABLE)
    }

    @Test
    fun matchesInferredColumnsAndQueryAliases() {
        listOf(
            "create table t (x) as select dummy from dual",
            "create table t (x, y) as select 1, 2 from dual",
            "create table t as select dummy from dual",
            "create table t as select 1 + 2 total from dual",
            "create table t (\"X\", annotations, invisible) as select 1, 2, 3 from dual",
            "create table t (definition, reservable) as " +
                "select definition as reservable, reservable as definition from source_table",
            "create table t (x) as (select 1 from dual)",
            // Column-count mismatches are ORA-01730 validation, not malformed column lists.
            "create table t (x, y) as select 1 from dual",
            "create table t (x) as select 1, 2 from dual"
        ).forEach { assertThat(p).matches(it) }
    }

    @Test
    fun matchesColumnAttributesAndInlineConstraints() {
        listOf(
            "default 7", "default on null 7", "default on null for insert only 7",
            "default on null for insert and update 7", "sort", "sort sort", "visible",
            "sort visible default 7", "visible sort", "null", "not null", "unique", "primary key",
            "check (x > 0)", "constraint nn not null enable validate",
            "constraint pk primary key deferrable initially deferred rely disable novalidate",
            "default 7 not null unique check (x > 0)",
            // These parse in Oracle but CTAS/table validation or wallet configuration rejects them.
            "annotations (note 'v')", "encrypt using 'AES256' 'NOMAC' no salt",
            "default 7 not null annotations (note 'v')", "references parent (x)",
            "constraint fk references parent (x)", "scope is parent", "with rowid",
            "generated always as identity", "sort generated by default as identity",
            "reservable", "visible reservable"
        ).forEach { assertThat(p).matches("create table t (x $it) as select 1 from dual") }
        assertThat(p).matches("create table t (x invisible, y) as select 1, 2 from dual")
    }

    @Test
    fun matchesTableConstraintsAndPhysicalProperties() {
        listOf(
            "(x, constraint pk primary key (x))",
            "(constraint pk primary key (x), x)",
            "(check (x > 0), x, y not null, unique (y))",
            "(x, foreign key (x) references parent (x))",
            "(x, supplemental log data (all) columns)",
            "(x, supplemental log group g (x) always)"
        ).forEach { assertThat(p).matches("create table t $it as select 1 x from dual") }
        assertThat(p).matches(
            "create table t (x default 1) segment creation deferred tablespace users nologging parallel " +
                "partition by hash (x) partitions 2 annotations (a 'b') as select 1 from dual")
    }

    @Test
    fun rejectsRelationalPropertiesWithoutExplicitColumnDefinitions() {
        // Oracle 26ai 23.26.3 rejects these with ORA-03079: missing required column definition list.
        // Even nonexistent aliases hit this syntax boundary, not name resolution (ORA-00904).
        listOf(
            "(primary key (x))",
            "(constraint pk primary key (x))",
            "(unique (x))",
            "(check (x > 0))",
            "(primary key (missing_alias))",
            "(check (missing_alias > 0))",
            "(primary key (x), unique (y), check (x > 0))",
            "(constraint pk primary key (x), constraint uq unique (y), constraint ck check (x > 0))",
            "(supplemental log data (all) columns)",
            "(supplemental log group lg (x) always)",
            "(supplemental log data (all) columns, supplemental log group lg (x))",
            "(primary key (x), supplemental log data (all) columns)"
        ).forEach { properties ->
            assertThat(p).notMatches("create table t $properties as select 1 x, 2 y from dual")
        }
        listOf(
            "(scope for (r) is scope_table)",
            "(ref (r) with rowid)",
            "(ref (r) with rowid, supplemental log data (all) columns)"
        ).forEach { properties ->
            assertThat(p).notMatches("create table t $properties as select r from ref_source")
        }
        // With an explicit column, an unresolved constraint name is no longer a syntax error.
        assertThat(p).matches("create table t (x, primary key (missing_alias)) as select 1 x from dual")
        assertThat(p).matches("create table t (x, check (missing_alias > 0)) as select 1 x from dual")
    }

    @Test
    fun matchesIndexOrganizedAndTemporaryVariants() {
        assertThat(p).matches("create table t (x primary key) organization index as select 1 from dual")
        assertThat(p).matches("create table t (x, primary key (x)) organization index as select 1 from dual")
        // The required IOT primary key is database validation (ORA-25175), not parser state.
        assertThat(p).matches("create table t (x) organization index as select 1 from dual")
        assertThat(p).matches("create global temporary table t (x) on commit preserve rows as select 1 from dual")
        assertThat(p).matches("create global temporary table t (x) on commit delete rows as select 1 from dual")
        assertThat(p).matches("create private temporary table ora\$ptt_t (x) as select 1 from dual")
        assertThat(p).matches(
            "create private temporary table ora\$ptt_t (x) on commit preserve definition as select 1 from dual")
        assertThat(p).matches(
            "create private temporary table ora\$ptt_t (x) on commit drop definition as select 1 from dual")
        assertThat(p).notMatches(
            "create private temporary table ora\$ptt_t (x) on commit preserve rows as select 1 from dual")
        assertThat(p).notMatches(
            "create global temporary table t (x) on commit preserve definition as select 1 from dual")
    }

    @Test
    fun matchesCtasUnderLedgerAndOutlinePrefixes() {
        assertThat(p).matches(
            "create immutable table t (x) no drop no delete as select 1 from dual")
        assertThat(p).matches(
            "create blockchain table t (x) no drop no delete hashing using sha2_512 version v2 " +
                "as select 1 from dual")
        setRootRule(DdlGrammar.CREATE_OUTLINE)
        assertThat(p).matches("create outline o on create table t (x) as select 1 from dual")
        assertThat(p).notMatches("create outline o on create table t (x number)")
    }

    @Test
    fun requiresSubqueryOnlyForDatatypeLessColumns() {
        listOf(
            "create table t (x)", "create table t (x, y)", "create table t (x not null)",
            "create table t (x default 1)", "create table t (x primary key) organization index",
            "create table t (x) tablespace users", "create table t (x) as",
            "create table t (x) as select", "create table t (x number) as select 1 from dual",
            "create table t (x, y number) as select 1, 2 from dual",
            "create table t (x number, y) as select 1, 2 from dual"
        ).forEach { assertThat(p).notMatches(it) }
        assertThat(p).matches("create table t (x number, y custom_type)")
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).matches("x number")
        assertThat(p).notMatches("x")
        assertThat(p).notMatches("x not null")
        setRootRule(DdlGrammar.DDL_COMMAND)
        assertThat(p).notMatches("alter table t add (x)")
    }

    @Test
    fun rejectsMalformedColumnListsAndAttributes() {
        listOf(
            "()", "(x,)", "(x,, y)", "(x default)", "(x visible invisible)",
            "(x not null default 1)", "(x annotations (a 'b') not null)", "(x collate binary)",
            "(x constraint nn)", "(x primary)", "(x check ())", "(x encrypt using)",
            "(x annotations ())", "(x default 1 generated always as identity)"
        ).forEach { assertThat(p).notMatches("create table t $it as select 1 from dual") }
    }

    @Test
    fun separatesConventionalAndCtasColumnsInLongLists() {
        val names = (1..512).joinToString(", ") { "c$it" }
        val typed = (1..512).joinToString(", ") { "c$it number" }
        assertThat(p).matches("create table t ($names) parallel as select * from source_table")
        assertThat(p).matches("create table t ($typed) parallel")
        assertThat(p).notMatches("create table t ($names) parallel")
        assertThat(p).notMatches("create table t ($typed) parallel as select * from source_table")
        assertThat(p).notMatches("create table t ($names,) as select * from source_table")
    }

    @Test
    fun keepsInferredColumnsDistinctFromTypedColumnAst() {
        val ctas = p.parse("create table t (x default 7 not null, y) as select 1, 2 from dual")
        val columns = ctas.getDescendants(DdlGrammar.CTAS_COLUMN_DEFINITION)
        assertAst(columns.map { it.getFirstChild(PlSqlGrammar.IDENTIFIER_NAME).token.originalValue })
            .containsExactly("x", "y")
        assertAst(columns.flatMap { it.getDescendants(PlSqlGrammar.DATATYPE) }).isEmpty()
        assertAst(columns[0].getFirstChild(PlSqlGrammar.LITERAL).tokenValue).isEqualTo("7")
        assertAst(columns[0].hasDirectChildren(DdlGrammar.INLINE_CONSTRAINT)).isTrue()
        assertAst(ctas.getDescendants(DdlGrammar.TABLE_COLUMN_DEFINITION)).isEmpty()

        val ordinary = p.parse("create table t (x number default 7 not null)")
        val column = ordinary.getFirstDescendant(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertAst(column.hasDirectChildren(PlSqlGrammar.DATATYPE)).isTrue()
        assertAst(ordinary.getDescendants(DdlGrammar.CTAS_COLUMN_DEFINITION)).isEmpty()
    }

    @Test
    fun parsesFollowingStatementsWithoutLeakingCtasMode() {
        setRootRule(PlSqlGrammar.FILE_INPUT)
        assertThat(p).matches(
            "create table t (x) as select 1 from dual; drop table t; create table t (x number);")
        assertThat(p).notMatches(
            "create table t (x) as select 1 from dual; create table invalid_table (x);")
    }
}
