/**
 * Z PL/SQL Analyzer
 * Copyright (C) 2015-2026 Felipe Zorzo
 * mailto:felipe AT felipezorzo DOT com DOT br
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.felipebz.zpa.api.ddl

import com.felipebz.flr.tests.Assertions.assertThat
import com.felipebz.zpa.api.DdlGrammar
import com.felipebz.zpa.api.RuleTest
import org.junit.jupiter.api.Test

class IdentityColumnTest : RuleTest() {

    @Test
    fun matchesGeneratedForms() {
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).matches("id number generated as identity")
        assertThat(p).matches("id number generated always as identity")
        assertThat(p).matches("id number generated by default as identity")
        assertThat(p).matches("id number generated by default on null as identity")
        assertThat(p).matches("id number generated by default on null for insert only as identity")
        assertThat(p).matches("id number generated by default on null for insert and update as identity")
    }

    @Test
    fun rejectsMalformedGeneratedForms() {
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).notMatches("id number generated always on null as identity")
        assertThat(p).notMatches("id number generated on null as identity")
        assertThat(p).notMatches("id number generated by default for insert only as identity")
        assertThat(p).notMatches("id number generated by default on null for (insert only) as identity")
        assertThat(p).notMatches("id number generated always as")
        assertThat(p).notMatches("id number generated always identity")
        assertThat(p).notMatches("id number identity")
        assertThat(p).notMatches("id number as identity")
        assertThat(p).notMatches("id number generated always as identity generated always as identity")
    }

    @Test
    fun matchesIdentityOptions() {
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).matches("id number generated always as identity ()")
        assertThat(p).matches("id number generated always as identity (start with 1)")
        assertThat(p).matches("id number generated by default on null as identity (start with 101 increment by 1 cycle cache 200)")
        assertThat(p).matches(
            "id number generated always as identity (start with 1 increment by 2 maxvalue 100 minvalue 1 cycle cache 20 order)")
        assertThat(p).matches("id number generated always as identity (nomaxvalue nominvalue nocycle nocache noorder)")
        assertThat(p).matches("id number generated always as identity (keep nokeep)")
        assertThat(p).matches("id number generated always as identity (scale extend)")
        assertThat(p).matches("id number generated always as identity (scale noextend)")
        assertThat(p).matches("id number generated always as identity (scale)")
        assertThat(p).matches("id number generated always as identity (noscale)")
        assertThat(p).matches("id number generated always as identity (restart)")
        assertThat(p).matches("id number generated always as identity (start with -5 increment by +1 maxvalue - 10)")
    }

    @Test
    fun matchesOptionsWithoutParentheses() {
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).matches("id number generated always as identity start with 1")
        assertThat(p).matches("id number generated always as identity cache 5 start with 1 order")
        assertThat(p).matches("id number generated by default as identity start with 1 maxvalue 100 not null")
    }

    @Test
    fun acceptsDuplicatesAndValuesCheckedAfterParsing() {
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).matches("id number generated always as identity (start with 1 start with 2)")
        assertThat(p).matches("id number generated always as identity (cycle nocycle)")
        assertThat(p).matches("id number generated always as identity (maxvalue 1 nomaxvalue)")
        assertThat(p).matches("id number generated always as identity (scale extend noscale)")
        assertThat(p).matches("id number generated always as identity (start with 1.5)")
        assertThat(p).matches("id number generated always as identity (start with 1e2 increment by 5.)")
        assertThat(p).matches("id number generated always as identity (minvalue 5 maxvalue 1)")
        assertThat(p).matches("id number generated always as identity (cache 0)")
    }

    @Test
    fun rejectsMalformedIdentityOptions() {
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).notMatches("id number generated always as identity (start with 1, increment by 2)")
        assertThat(p).notMatches("id number generated always as identity (session)")
        assertThat(p).notMatches("id number generated always as identity (global)")
        assertThat(p).notMatches("id number generated always as identity (restart with 1)")
        assertThat(p).notMatches("id number generated always as identity (start with limit value)")
        assertThat(p).notMatches("id number generated always as identity (start with 'x')")
        assertThat(p).notMatches("id number generated always as identity (start with x)")
        assertThat(p).notMatches("id number generated always as identity (start with - -5)")
        assertThat(p).notMatches("id number generated always as identity (start with (1))")
        assertThat(p).notMatches("id number generated always as identity (start with)")
        assertThat(p).notMatches("id number generated always as identity (start 1)")
        assertThat(p).notMatches("id number generated always as identity (increment 1)")
        assertThat(p).notMatches("id number generated always as identity (cache)")
        assertThat(p).notMatches("id number generated always as identity (maxvalue)")
        assertThat(p).notMatches("id number generated always as identity (garbage)")
        assertThat(p).notMatches("id number generated always as identity (start with 1) (cache 5)")
        assertThat(p).notMatches("id number generated always as identity (cache 5) start with 1")
    }

    @Test
    fun placesIdentityAmongColumnProperties() {
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).matches("id number generated always as identity not null")
        assertThat(p).matches("id number generated always as identity primary key")
        assertThat(p).matches("id number generated by default on null as identity (start with 101) not null primary key")
        assertThat(p).matches("id number generated always as identity unique check (id > 0)")
        assertThat(p).matches("id number generated always as identity constraint c1 not null enable")
        assertThat(p).matches("id number sort generated always as identity")
        assertThat(p).matches("id number generated always as identity encrypt")
        assertThat(p).matches("id number generated always as identity annotations (a 'b')")
        assertThat(p).notMatches("id number default 1 generated always as identity")
        assertThat(p).notMatches("id number generated always as identity default 1")
        assertThat(p).notMatches("id number not null generated always as identity")
        assertThat(p).notMatches("id number primary key generated always as identity")
        assertThat(p).notMatches("id number constraint c1 not null generated always as identity")
        assertThat(p).notMatches("id number encrypt generated always as identity")
    }

    @Test
    fun acceptsIdentityWithoutDatatype() {
        setRootRule(DdlGrammar.TABLE_COLUMN_DEFINITION)
        assertThat(p).matches("id generated always as identity")
        assertThat(p).matches("id generated by default on null as identity (start with 1) primary key")
        assertThat(p).notMatches("id not null")
        assertThat(p).notMatches("id")
        assertThat(p).notMatches("id generated always as identity garbage")
    }

    @Test
    fun keepsColumnsNamedLikeIdentityKeywords() {
        setRootRule(DdlGrammar.CREATE_TABLE)
        assertThat(p).matches("create table t (generated number, always number, identity number)")
        assertThat(p).matches("create table t (id number generated always as identity, generated varchar2(10))")
    }

    @Test
    fun matchesCreateAndAddColumn() {
        setRootRule(DdlGrammar.DDL_COMMAND)
        assertThat(p).matches("create table t1 (id number generated as identity);")
        assertThat(p).matches("create table t2 (id number generated by default as identity (start with 100 increment by 10));")
        assertThat(p).matches(
            "create table products (id number(4) generated by default on null as identity " +
                "(start with 101 increment by 1 cycle cache 200) not null primary key, name varchar2(255) not null);")
        assertThat(p).matches("create table t (order_id number(10) generated by default as identity start with 1 maxvalue 100, x number);")
        assertThat(p).matches("alter table t add (id number generated always as identity);")
        assertThat(p).matches("alter table t add id number generated by default on null as identity (start with 5) not null;")
        assertThat(p).matches("alter table t add (id generated always as identity);")
        assertThat(p).notMatches("alter table t add (id number generated always as identity (start with limit value));")
    }

    @Test
    fun matchesModifyColumn() {
        setRootRule(DdlGrammar.DDL_COMMAND)
        assertThat(p).matches("alter table t modify (x generated by default as identity);")
        assertThat(p).matches("alter table t modify (x generated by default on null as identity (cache 5));")
        assertThat(p).matches("alter table t modify (x generated always as identity (increment by 2));")
        assertThat(p).matches("alter table t modify (x number generated always as identity);")
        assertThat(p).matches("alter table t modify x generated always as identity;")
        assertThat(p).matches("alter table t modify (x generated always as identity (start with limit value));")
        assertThat(p).matches("alter table t modify (x generated always as identity (start with limit value cache 5));")
        assertThat(p).notMatches("alter table t modify (x generated always as identity (start limit value));")
        assertThat(p).notMatches("alter table t modify (x generated always as identity (start with limit));")
    }
}
