/**
 * Z PL/SQL Analyzer
 * Copyright (C) 2015-2026 Felipe Zorzo
 * mailto:felipe AT felipezorzo DOT com DOT br
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.felipebz.zpa.api.ddl

import com.felipebz.flr.tests.Assertions.assertThat
import com.felipebz.zpa.api.DdlGrammar
import com.felipebz.zpa.api.PlSqlGrammar
import com.felipebz.zpa.api.RuleTest
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.assertj.core.api.Assertions.assertThat as assertThatAst

class VirtualColumnTest : RuleTest() {

    @BeforeEach
    fun init() {
        setRootRule(DdlGrammar.VIRTUAL_COLUMN_DEFINITION)
    }

    @Test
    fun matchesDatatypePresentAndOmittedForms() {
        assertThat(p).matches("c number as (a + 1)")
        assertThat(p).matches("c number generated always as (a + 1)")
        assertThat(p).matches("c as (a + 1)")
        assertThat(p).matches("c generated always as (a + 1)")
        assertThat(p).matches("c varchar2(10) as (to_char(a))")
        assertThat(p).matches("c varchar2(10) collate binary_ci as (to_char(a))")
        assertThat(p).matches("c number as (json_value(data, '$.n.number()' error on error))")
    }

    @Test
    fun matchesStorageKeywords() {
        for (keyword in listOf("virtual", "materialized", "stored")) {
            assertThat(p).matches("c number as (a + 1) $keyword")
            assertThat(p).matches("c generated always as (a + 1) $keyword")
        }
    }

    @Test
    fun matchesVisibilityBeforeExpression() {
        assertThat(p).matches("c number visible as (a + 1)")
        assertThat(p).matches("c number invisible as (a + 1)")
        assertThat(p).matches("c number invisible generated always as (a + 1)")
        assertThat(p).matches("c invisible as (a + 1)")
        assertThat(p).matches("c visible as (a + 1) virtual")
    }

    @Test
    fun matchesEditionClausesInOrder() {
        assertThat(p).matches("c number as (a + 1) evaluate using current edition")
        assertThat(p).matches("c number as (a + 1) evaluate using edition e1")
        assertThat(p).matches("c number as (a + 1) evaluate using null edition")
        assertThat(p).matches("c number as (a + 1) unusable before current edition")
        assertThat(p).matches("c number as (a + 1) unusable before edition e1")
        assertThat(p).matches("c number as (a + 1) unusable beginning with current edition")
        assertThat(p).matches("c number as (a + 1) unusable beginning with edition e1")
        assertThat(p).matches("c number as (a + 1) unusable beginning with null edition")
        assertThat(p).matches(
            "c number as (a + 1) virtual evaluate using current edition " +
                "unusable before edition e1 unusable beginning with null edition not null")
    }

    @Test
    fun matchesInlineConstraints() {
        assertThat(p).matches("c number as (a + 1) not null")
        assertThat(p).matches("c number as (a + 1) check (c > 0)")
        assertThat(p).matches("c number as (a + 1) constraint k unique")
        assertThat(p).matches("c number as (a + 1) virtual not null check (c > 0)")
        assertThat(p).matches("c number as (a + 1) primary key")
    }

    @Test
    fun rejectsMalformedAndMisorderedClauses() {
        assertThat(p).notMatches("c number as a + 1")
        assertThat(p).notMatches("c number as ()")
        assertThat(p).notMatches("c number as (a + 1) generated")
        assertThat(p).notMatches("c number generated as (a + 1)")
        assertThat(p).notMatches("c number generated by default as (a + 1)")
        assertThat(p).notMatches("c number generated always as identity")
        assertThat(p).notMatches("c number default 1 as (a + 1)")
        assertThat(p).notMatches("c number not null as (a + 1)")
        assertThat(p).notMatches("c number as (a + 1) virtual virtual")
        assertThat(p).notMatches("c number as (a + 1) materialized virtual")
        assertThat(p).notMatches("c number as (a + 1) stored materialized")
        assertThat(p).notMatches("c number visible invisible as (a + 1)")
        assertThat(p).notMatches("c number as (a + 1) invisible")
        assertThat(p).notMatches("c collate binary_ci as (a + 1)")
        assertThat(p).notMatches("c number as (a + 1) evaluate using null edition evaluate using current edition")
        assertThat(p).notMatches("c number as (a + 1) unusable beginning with null edition unusable before current edition")
        assertThat(p).notMatches("c number as (a + 1) unusable before null edition")
        assertThat(p).notMatches("c number as (a + 1) evaluate using")
        assertThat(p).notMatches("c number as (a + 1) unusable before current")
        assertThat(p).notMatches("c number unusable before current edition as (a + 1)")
        assertThat(p).notMatches("c number as (a + 1) not null virtual")
        assertThat(p).notMatches("c number as (a + 1), d number")
        assertThat(p).notMatches("as (a + 1)")
    }

    @Test
    fun integratesWithCreateAndAlterTable() {
        setRootRule(PlSqlGrammar.FILE_INPUT)
        assertThat(p).matches("create table t (a number, c number as (a + 1), d as (a * 2) virtual);")
        assertThat(p).matches("create table t (a number, c number generated always as (a + 1) materialized, constraint pk primary key (a));")
        assertThat(p).matches("create table t (c as (1), a number);")
        assertThat(p).matches("create table t (virtual number as (1), visible as (2), generated as (3));")
        assertThat(p).matches("alter table t add (c number as (a + 1));")
        assertThat(p).matches("alter table t add c number as (a + 1);")
        assertThat(p).matches("alter table t add c generated always as (a + 1);")
        assertThat(p).matches("alter table t add (a number, c as (a + 1) virtual, d number);")
    }

    @Test
    fun keepsIdentityColumnsDistinct() {
        setRootRule(PlSqlGrammar.FILE_INPUT)
        val tree = p.parse("create table t (a number generated always as identity, " +
            "b number generated by default on null as identity (start with 5), " +
            "c number as (a + 1), d generated always as (a + 2) virtual, " +
            "e varchar2(5) not null);")
        assertThatAst(tree.getDescendants(DdlGrammar.TABLE_COLUMN_DEFINITION)).hasSize(3)
        val virtual = tree.getDescendants(DdlGrammar.VIRTUAL_COLUMN_DEFINITION)
        assertThatAst(virtual.map { it.getFirstChild(PlSqlGrammar.IDENTIFIER_NAME).tokenValue }).containsExactly("C", "D")
        assertThatAst(virtual[0].getChildren(PlSqlGrammar.DATATYPE)).hasSize(1)
        assertThatAst(virtual[1].getChildren(PlSqlGrammar.DATATYPE)).isEmpty()
    }
}
