/**
 * Z PL/SQL Analyzer
 * Copyright (C) 2015-2026 Felipe Zorzo
 * mailto:felipe AT felipezorzo DOT com DOT br
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.felipebz.zpa.api

import com.felipebz.flr.api.AstNode
import com.felipebz.flr.api.TokenType

enum class PlSqlKeyword(override val value: String, val isReserved: Boolean = false) : TokenType {
    ALL("all", true),
    ALTER("alter", true),
    AND("and", true),
    ANY("any", true),
    AS("as", true),
    ASC("asc", true),
    BEGIN("begin", true),
    BETWEEN("between", true),
    BY("by", true),
    CHAR("char"),
    CHECK("check", true),
    CLUSTER("cluster", true),
    COMPRESS("compress", true),
    CONNECT("connect", true),
    CREATE("create", true),
    DECLARE("declare", true),
    DEFAULT("default", true),
    DESC("desc", true),
    DISTINCT("distinct", true),
    DROP("drop", true),
    ELSE("else", true),
    END("end", true),
    EXCEPT("except"),
    EXCLUSIVE("exclusive", true),
    FETCH("fetch", true),
    FLOAT("float"),
    FOR("for", true),
    FROM("from", true),
    GRANT("grant", true),
    GROUP("group", true),
    HAVING("having", true),
    IDENTIFIED("identified", true),
    IN("in", true),
    INDEX("index", true),
    INSERT("insert", true),
    INTEGER("integer"),
    INTERSECT("intersect", true),
    INTO("into", true),
    IS("is", true),
    LIKE("like", true),
    LOCK("lock", true),
    LONG("long"),
    MINUS_KEYWORD("minus", true),
    NOCOMPRESS("nocompress", true),
    NOT("not", true),
    NOWAIT("nowait", true),
    NULL("null", true),
    OF("of", true),
    ON("on", true),
    OPTION("option", true),
    OR("or", true),
    ORDER("order", true),
    OUT("out"),
    PCTFREE("pctfree"),
    PRIOR("prior"),
    PROCEDURE("procedure", true),
    PUBLIC("public", true),
    RAW("raw"),
    RESOURCE("resource", true),
    REVOKE("revoke", true),
    SELECT("select", true),
    SHARE("share", true),
    SIZE("size", true),
    SMALLINT("smallint"),
    START("start", true),
    SYNONYM("synonym"),
    TABLE("table", true),
    THEN("then", true),
    TO("to", true),
    TRIGGER("trigger", true),
    UNION("union", true),
    UNIQUE("unique", true),
    UPDATE("update", true),
    VALUES("values", true),
    VIEW("view", true),
    WHEN("when", true),
    WHERE("where", true),
    WITH("with", true),
    A("a"),
    ABSENT("absent"),
    ACCESS("access"),
    ACCESSIBLE("accessible"),
    ADD("add"),
    ADMIN("admin"),
    ADVANCED("advanced"),
    AFTER("after"),
    AGENT("agent"),
    AGGREGATE("aggregate"),
    ALLOCATE("allocate"),
    ALLOW("allow"),
    ANALYZE("analyze"),
    ANNOTATIONS("annotations"),
    ANY_CS("any_cs"),
    ANYSCHEMA("anyschema"),
    APPEND("append"),
    ARRAY("array"),
    ARROW("arrow"),
    ASCII("ascii"),
    ASSOCIATE("associate"),
    AT("at"),
    ATTRIBUTES("attributes"),
    AUDIT("audit"),
    AUTHID("authid"),
    AUTOMATIC("automatic"),
    AUTONOMOUS_TRANSACTION("autonomous_transaction"),
    BATCH("batch"),
    BEGINNING("beginning"),
    BEQUEATH("bequeath"),
    BEFORE("before"),
    BFILE("bfile"),
    BINARY("binary"),
    BINARY_DOUBLE("binary_double"),
    BINARY_DOUBLE_INFINITY("binary_double_infinity"),
    BINARY_DOUBLE_NAN("binary_double_nan"),
    BINARY_FLOAT("binary_float"),
    BINARY_FLOAT_INFINITY("binary_float_infinity"),
    BINARY_FLOAT_NAN("binary_float_nan"),
    BINARY_INTEGER("binary_integer"),
    BITMAP("bitmap"),
    BLOB("blob"),
    BLOCK("block"),
    BODY("body"),
    BOOLEAN("boolean"),
    BOTH("both"),
    BREADTH("breadth"),
    BUFFER_POOL("buffer_pool"),
    BUILD("build"),
    BULK("bulk"),
    BULK_ROWCOUNT("bulk_rowcount"),
    BYTE("byte"),
    CACHE("cache"),
    CASCADE("cascade"),
    CASE("case"),
    CASE_SENSITIVE("case_sensitive"),
    CAST("cast"),
    CELL_FLASH_CACHE("cell_flash_cache"),
    CHARACTER("character"),
    CHARSET("charset"),
    CHARSETFORM("charsetform"),
    CHARSETID("charsetid"),
    CHUNK("chunk"),
    CLEANUP("cleanup"),
    CLOB("clob"),
    CLONE("clone"),
    CLOSE("close"),
    CLUSTERS("clusters"),
    COALESCE("coalesce"),
    COLAUTH("colauth"),
    COLLATION("collation"),
    COLLECT("collect"),
    COLUMN("column"),
    COLUMNS("columns"),
    COLLECTION("collection"),
    COMMENT("comment"),
    COMMIT("commit"),
    COMMITTED("committed"),
    COMPACT("compact"),
    COMPILE("compile"),
    COMPLETE("complete"),
    COMPOUND("compound"),
    COMPUTATION("computation"),
    CONCURRENT("concurrent"),
    CONDITIONAL("conditional"),
    CONNECT_BY_ROOT("connect_by_root"),
    CONSTANT("constant"),
    CONSTRAINT("constraint"),
    CONSTRAINTS("constraints"),
    CONSTRUCTOR("constructor"),
    CONTAINER("container"),
    CONTAINER_MAP("container_map"),
    CONTAINERS_DEFAULT("containers_default"),
    CONTENT("content"),
    CONTEXT("context"),
    CONTINUE("continue"),
    CONVERSION("conversion"),
    COPY("copy"),
    COUNT("count"),
    COVERAGE("coverage"),
    CRASH("crash"),
    CREATION("creation"),
    CROSS("cross"),
    CROSSEDITION("crossedition"),
    CUBE("cube"),
    CURRENT("current"),
    CURRENT_USER("current_user"),
    CURRVAL("currval"),
    CURSOR("cursor"),
    CYCLE("cycle"),
    DATA("data"),
    DATABASE("database"),
    DATAFILE("datafile"),
    DATE("date"),
    DAY("day"),
    DAYS("days"),
    DB_ROLE_CHANGE("db_role_change"),
    DDL("ddl"),
    DEALLOCATE("deallocate"),
    DEBUG("debug"),
    DEC("dec"),
    DECIMAL("decimal"),
    DECREMENT("decrement"),
    DEFAULTS("defaults"),
    DEFERRABLE("deferrable"),
    DEFERRED("deferred"),
    DEFINER("definer"),
    DELEGATE("delegate"),
    DEMAND("demand"),
    DELETE("delete"),
    DELETE_ALL("delete_all"),
    DENSE("dense"),
    DENSE_RANK("dense_rank"),
    DEPRECATE("deprecate"),
    DEPTH("depth"),
    DETERMINISTIC("deterministic"),
    DIMENSION("dimension"),
    DIRECTORY("directory"),
    DISABLE("disable"),
    DISABLE_ALL("disable_all"),
    DISALLOW("disallow"),
    DISASSOCIATE("disassociate"),
    DOCUMENT("document"),
    DOMAIN("domain"),
    DOUBLE("double"),
    DURATION("duration"),
    EACH("each"),
    EDITION("edition"),
    EDITIONABLE("editionable"),
    EDITIONING("editioning"),
    ELEMENT("element"),
    ELSIF("elsif"),
    EMPTY("empty"),
    ENABLE("enable"),
    ENABLE_ALL("enable_all"),
    ENCODING("encoding"),
    ENFORCED("enforced"),
    ENCRYPT("encrypt"),
    ENTITYESCAPING("entityescaping"),
    ERROR("error"),
    ERRORS("errors"),
    ESCAPE("escape"),
    EVALNAME("evalname"),
    EVALUATE("evaluate"),
    EXCEPTION("exception"),
    EXCEPTIONS("exceptions"),
    EXCEPTION_INIT("exception_init"),
    EXCLUDE("exclude"),
    EXECUTE("execute"),
    EXISTING("existing"),
    EXISTS("exists"),
    EXIT("exit"),
    EXTEND("extend"),
    EXTENDED("extended"),
    EXTENT("extent"),
    EXTERNAL("external"),
    EXTRA("extra"),
    EXTRACT("extract"),
    FALSE("false"),
    FAST("fast"),
    FILTER("filter"),
    FINAL("final"),
    FIRST("first"),
    FLASH_CACHE("flash_cache"),
    FOLLOWING("following"),
    FOLLOWS("follows"),
    FORALL("forall"),
    FORCE("force"),
    FOREIGN("foreign"),
    FORM("form"),
    FORMAT("format"),
    FORWARD("forward"),
    FOUND("found"),
    FREELIST("freelist"),
    FREELISTS("freelists"),
    FREEPOOLS("freepools"),
    FULL("full"),
    FUNCTION("function"),
    GLOBAL("global"),
    GOTO("goto"),
    GROUPING("grouping"),
    GROUPS("groups"),
    HASH("hash"),
    HIDE("hide"),
    HIERARCHY("hierarchy"),
    HIGH("high"),
    HOUR("hour"),
    IF("if"),
    IGNORE("ignore"),
    ILM("ilm"),
    IMMEDIATE("immediate"),
    IMMUTABLE("immutable"),
    INCLUDE("include"),
    INCREMENT("increment"),
    INDENT("indent"),
    INDEXES("indexes"),
    INDEXING("indexing"),
    INDEXTYPE("indextype"),
    INDICATOR("indicator"),
    INDICES("indices"),
    INITIAL("initial"),
    INITIALLY("initially"),
    INITRANS("initrans"),
    INLINE("inline"),
    INNER("inner"),
    INSTANCE("instance"),
    INSTANTIABLE("instantiable"),
    INSTEAD("instead"),
    INT("int"),
    INTERFACE("interface"),
    INTERVAL("interval"),
    INVALIDATION("invalidation"),
    INVISIBLE("invisible"),
    ISOLATION("isolation"),
    ISOPEN("isopen"),
    ITERATE("iterate"),
    JAVA("java"),
    JOIN("join"),
    JSON("json"),
    JSON_ARRAY("json_array"),
    JSON_ARRAYAGG("json_arrayagg"),
    JSON_DATAGUIDE("json_dataguide"),
    JSON_EQUAL("json_equal"),
    JSON_EXISTS("json_exists"),
    JSON_MERGEPATCH("json_mergepatch"),
    JSON_OBJECT("json_object"),
    JSON_OBJECTAGG("json_objectagg"),
    JSON_QUERY("json_query"),
    JSON_SCALAR("json_scalar"),
    JSON_SERIALIZE("json_serialize"),
    JSON_TABLE("json_table"),
    JSON_TEXTCONTAINS("json_textcontains"),
    JSON_TRANSFORM("json_transform"),
    JSON_VALUE("json_value"),
    KEEP("keep"),
    KEY("key"),
    KEYS("keys"),
    LANGUAGE("language"),
    LAST("last"),
    LAX("lax"),
    LEADING("leading"),
    LEFT("left"),
    LENGTH("length"),
    LESS("less"),
    LEVEL("level"),
    LEVELS("levels"),
    LIBRARY("library"),
    LIMIT("limit"),
    LIST("list"),
    LISTAGG("listagg"),
    LOB("lob"),
    LOBS("lobs"),
    LOCAL("local"),
    LOCKED("locked"),
    LOG("log"),
    LOGGING("logging"),
    LOGOFF("logoff"),
    LOGON("logon"),
    LOOP("loop"),
    LOW("low"),
    LOW_COST_TBS("low_cost_tbs"),
    MAIN("main"),
    MAP("map"),
    MAPPING("mapping"),
    MASTER("master"),
    MATCHED("matched"),
    MATERIALIZED("materialized"),
    MAXEXTENTS("maxextents"),
    MAXLEN("maxlen"),
    MAXSIZE("maxsize"),
    MAXVALUE("maxvalue"),
    MEASURES("measures"),
    MEMBER("member"),
    MERGE("merge"),
    METADATA("metadata"),
    MINEXTENTS("minextents"),
    MINING("mining"),
    MINUTE("minute"),
    MINVALUE("minvalue"),
    MISMATCH("mismatch"),
    MISSING("missing"),
    MODE("mode"),
    MODEL("model"),
    MODIFICATION("modification"),
    MODIFY("modify"),
    MOD_KEYWORD("mod"),
    MONITORING("monitoring"),
    MONTH("month"),
    MONTHS("months"),
    MORE("more"),
    MULTISET("multiset"),
    MULTIVALUE("multivalue"),
    MUTABLE("mutable"),
    NAME("name"),
    NATURAL("natural"),
    NATURALN("naturaln"),
    NAV("nav"),
    NCHAR("nchar"),
    NCLOB("nclob"),
    NESTED("nested"),
    NEW("new"),
    NEXT("next"),
    NEXTVAL("nextval"),
    NEVER("never"),
    NO("no"),
    NOAUDIT("noaudit"),
    NOCACHE("nocache"),
    NOCOPY("nocopy"),
    NOCYCLE("nocycle"),
    NOENTITYESCAPING("noentityescaping"),
    NOEXTEND("noextend"),
    NOKEEP("nokeep"),
    NOLOGGING("nologging"),
    NOMAPPING("nomapping"),
    NOMAXVALUE("nomaxvalue"),
    NOMINVALUE("nominvalue"),
    NOMONITORING("nomonitoring"),
    NONE("none"),
    NONEDITIONABLE("noneditionable"),
    NONSCHEMA("nonschema"),
    NOORDER("noorder"),
    NOPARALLEL("noparallel"),
    NOPRECHECK("noprecheck"),
    NORELY("norely"),
    NOREVERSE("noreverse"),
    NOSCALE("noscale"),
    NOSCHEMACHECK("noschemacheck"),
    NOSORT("nosort"),
    NOTFOUND("notfound"),
    NOVALIDATE("novalidate"),
    NOW("now"),
    NULLS("nulls"),
    NUMBER("number"),
    NUMERIC("numeric"),
    NVARCHAR2("nvarchar2"),
    OBJECT("object"),
    OFFSET("offset"),
    OLD("old"),
    OMIT("omit"),
    ONLINE("online"),
    ONLY("only"),
    OPEN("open"),
    OPERATOR("operator"),
    OPTIMAL("optimal"),
    OPTIMIZE("optimize"),
    ORDERED("ordered"),
    ORDINALITY("ordinality"),
    OTHERS("others"),
    OUTER("outer"),
    OVER("over"),
    OVERFLOW("overflow"),
    OVERLAPS("overlaps"),
    OVERRIDING("overriding"),
    PACKAGE("package"),
    PAIRS("pairs"),
    PARALLEL("parallel"),
    PARALLEL_ENABLE("parallel_enable"),
    PARAMETERS("parameters"),
    PARENT("parent"),
    PARTIAL("partial"),
    PARTITION("partition"),
    PARTITIONS("partitions"),
    PASSING("passing"),
    PATH("path"),
    PCTINCREASE("pctincrease"),
    PCTUSED("pctused"),
    PCTVERSION("pctversion"),
    PERCENT("percent"),
    PIPE("pipe"),
    PIPELINED("pipelined"),
    PIVOT("pivot"),
    PLS_INTEGER("pls_integer"),
    PLUGGABLE("pluggable"),
    POLICY("policy"),
    POSITIVE("positive"),
    POSITIVEN("positiven"),
    PRAGMA("pragma"),
    PRECEDES("precedes"),
    PRECEDING("preceding"),
    PRECHECK("precheck"),
    PREBUILT("prebuilt"),
    PRECISION("precision"),
    PREPEND("prepend"),
    PRESENT("present"),
    PRESERVE("preserve"),
    PRETTY("pretty"),
    PRIMARY("primary"),
    QUERY("query"),
    PURGE("purge"),
    QUOTES("quotes"),
    RAISE("raise"),
    RANGE_KEYWORD("range"),
    READ("read"),
    READS("reads"),
    REAL("real"),
    REBUILD("rebuild"),
    RECORD("record"),
    RECYCLE("recycle"),
    REF("ref"),
    REDUCED("reduced"),
    REFERENCE("reference"),
    REFERENCES("references"),
    REFERENCING("referencing"),
    REFRESH("refresh"),
    REJECT("reject"),
    RELIES_ON("relies_on"),
    RELY("rely"),
    REMOVE("remove"),
    RENAME("rename"),
    REPEAT("repeat"),
    REPLACE("replace"),
    REWRITE("rewrite"),
    RESTRICT_REFERENCES("restrict_references"),
    RESULT("result"),
    RESULT_CACHE("result_cache"),
    RETENTION("retention"),
    RETURN("return"),
    RETURNING("returning"),
    REUSE("reuse"),
    REVERSE("reverse"),
    RIGHT("right"),
    ROLE("role"),
    ROLLBACK("rollback"),
    ROLLUP("rollup"),
    ROW("row"),
    ROWCOUNT("rowcount"),
    ROWID("rowid"),
    ROWNUM("rownum"),
    ROWS("rows"),
    ROWTYPE("rowtype"),
    RULES("rules"),
    SAVE("save"),
    SAVEPOINT("savepoint"),
    SALT("salt"),
    SCALAR("scalar"),
    SCALARS("scalars"),
    SCALE("scale"),
    SCHEMA("schema"),
    SCOPE("scope"),
    SCHEMACHECK("schemacheck"),
    SDO_GEOMETRY("sdo_geometry"),
    SEARCH("search"),
    SECOND("second"),
    SEGMENT("segment"),
    SELF("self"),
    SEQUENCE("sequence"),
    SEQUENTIAL("sequential"),
    SERIALIZABLE("serializable"),
    SERIALLY_REUSABLE("serially_reusable"),
    SERVERERROR("servererror"),
    SESSION("session"),
    SET("set"),
    SETS("sets"),
    SETTINGS("settings"),
    SHARING("sharing"),
    SHOW("show"),
    SHRINK("shrink"),
    SHUTDOWN("shutdown"),
    SIBLINGS("siblings"),
    SIGNTYPE("signtype"),
    SINGLE("single"),
    SINGLEVALUE("singlevalue"),
    SKIP("skip"),
    SOME("some"),
    SORT("sort"),
    SPARSE("sparse"),
    SPACE("space"),
    SPECIFICATION("specification"),
    SPLIT("split"),
    SQL("sql"),
    SQLERRM("sqlerrm"),
    STANDALONE("standalone"),
    STARTUP("startup"),
    STATEMENT_KEYWORD("statement"),
    STATIC("static"),
    STATISTICS("statistics"),
    STORAGE("storage"),
    STORE("store"),
    STRICT("strict"),
    STRING("string"),
    STRUCT("struct"),
    SUBMULTISET("submultiset"),
    SUBPARTITION("subpartition"),
    SUBPARTITIONS("subpartitions"),
    SUBSTITUTABLE("substitutable"),
    SUBTYPE("subtype"),
    SUPPRESSES_WARNING_6009("suppresses_warning_6009"),
    SUSPEND("suspend"),
    SYSDATE("sysdate"),
    TABAUTH("tabauth"),
    TABLES("tables"),
    TABLESPACE("tablespace"),
    TDO("tdo"),
    TEMPLATE("template"),
    TEMPORARY("temporary"),
    THAN("than"),
    THE("the"),
    TIER("tier"),
    TIES("ties"),
    TIME("time"),
    TIMESTAMP("timestamp"),
    TO_BINARY_DOUBLE("to_binary_double"),
    TO_BINARY_FLOAT("to_binary_float"),
    TO_BOOLEAN("to_boolean"),
    TO_DATE("to_date"),
    TO_DSINTERVAL("to_dsinterval"),
    TO_NUMBER("to_number"),
    TO_TIMESTAMP("to_timestamp"),
    TO_TIMESTAMP_TZ("to_timestamp_tz"),
    TO_YMINTERVAL("to_yminterval"),
    TRAILING("trailing"),
    TRANSACTION("transaction"),
    TREAT("treat"),
    TRIM("trim"),
    TRUE("true"),
    TRUNCATE("truncate"),
    TRUSTED("trusted"),
    TYPE("type"),
    TYPENAME("typename"),
    UDF("udf"),
    UNBOUNDED("unbounded"),
    UNCONDITIONAL("unconditional"),
    UNDER("under"),
    UNLIMITED("unlimited"),
    UNPIVOT("unpivot"),
    UNPLUG("unplug"),
    UNTIL("until"),
    UNUSABLE("unusable"),
    UNUSED("unused"),
    UPDATED("updated"),
    UPSERT("upsert"),
    UROWID("urowid"),
    USABLE("usable"),
    USAGE("usage"),
    USE("use"),
    USING("using"),
    USING_NLS_COMP("using_nls_comp"),
    VALIDATE("validate"),
    VALUE("value"),
    VARCHAR("varchar"),
    VARCHAR2("varchar2"),
    VARRAY("varray"),
    VARRAYS("varrays"),
    VARYING("varying"),
    VECTOR("vector"),
    VERSION("version"),
    VIEWS("views"),
    VISIBLE("visible"),
    WAIT("wait"),
    WELLFORMED("wellformed"),
    WHILE("while"),
    WITHIN("within"),
    WITHOUT("without"),
    WORK("work"),
    WRAPPER("wrapper"),
    WRITE("write"),
    XDB("xdb"),
    XML("xml"),
    XMLAGG("xmlagg"),
    XMLATTRIBUTES("xmlattributes"),
    XMLCAST("xmlcast"),
    XMLCDATA("xmlcdata"),
    XMLCOLATTVAL("xmlcolattval"),
    XMLCOMMENT("xmlcomment"),
    XMLCONCAT("xmlconcat"),
    XMLDIFF("xmldiff"),
    XMLELEMENT("xmlelement"),
    XMLEXISTS("xmlexists"),
    XMLFOREST("xmlforest"),
    XMLINDEX("xmlindex"),
    XMLISVALID("xmlisvalid"),
    XMLNAMESPACES("xmlnamespaces"),
    XMLPARSE("xmlparse"),
    XMLPATCH("xmlpatch"),
    XMLPI("xmlpi"),
    XMLQUERY("xmlquery"),
    XMLROOT("xmlroot"),
    XMLSCHEMA("xmlschema"),
    XMLSEQUENCE("xmlsequence"),
    XMLSERIALIZE("xmlserialize"),
    XMLTABLE("xmltable"),
    XMLTRANSFORM("xmltransform"),
    XMLTYPE("xmltype"),
    YEAR("year"),
    YEARS("years"),
    YES("yes"),
    ZONE("zone");

    override fun hasToBeSkippedFromAst(node: AstNode?) = false

    companion object {
        val keywordValues: List<String> =
            entries.map { it.value }

        val nonReservedKeywords: List<PlSqlKeyword> =
            entries.filter { !it.isReserved }
    }
}
