select custom_function(),
       custom_function(1),
       custom_function(a, b, c),
       package.custom_function(),
       package.custom_function(1, 'two'),
       "schema"."package".custom_function(1),
       obj.method(x => 1),
       "custom_function"(1),
       "schema"."package"."custom_function"(1),
       count(distinct emp_id),
       count(*),
       outer_function(inner_function(1)),
       pkg.proc@link(),
       pkg.proc@link.domain(),
       pkg.proc@link.domain.com(),
       foo(1)(2),
       named_distinct(x => distinct value),
       sum(salary),
       to_char(sysdate),
       to_date('2026-09-03', 'YYYY-MM-DD'),
       listagg(employee_name) within group (order by employee_name)
  from dual;
