-- https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/ALTER-TABLE.html
ALTER TABLE employee RESULT_CACHE (MODE DEFAULT) 
    ALTER TABLE employee RESULT_CACHE (STANDBY ENABLE)   
    ALTER TABLE employee RESULT_CACHE (MODE DEFAULT, STANDBY ENABLE)
    ALTER TABLE employee RESULT_CACHE (STANDBY ENABLE, MODE FORCE)