-- https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/create-property-graph.html
CREATE TABLE EMP(
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(10),
  AGE NUMBER,
  DEPARTMENT NUMBER,
  MANAGER NUMBER,
  CONSTRAINT emp_fk_mgr FOREIGN KEY(MANAGER) REFERENCES EMP(id)
);
INSERT INTO EMP VALUES(1, 'Alex', 25, 1, NULL);
INSERT INTO EMP VALUES(2, 'Bob', 27, 1, 1);
INSERT INTO EMP VALUES(3, 'Craig', 26, 2, NULL);
INSERT INTO EMP VALUES(4, 'Dan', 24, 2, 3);
INSERT INTO EMP VALUES(5, 'Erin', 25, 2, 3);
commit;
CREATE TABLE DPT(
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(10)
);
INSERT INTO DPT VALUES(1, 'IT');
INSERT INTO DPT VALUES(2, 'Sales');
commit;
CREATE TABLE FOF(
  ID NUMBER PRIMARY KEY,
  SRC NUMBER,  
  DST NUMBER,
  E_COST NUMBER,
  CONSTRAINT fof_fk_src FOREIGN KEY(SRC) REFERENCES EMP(ID),
  CONSTRAINT fof_fk_dst FOREIGN KEY(DST) REFERENCES EMP(ID)
);
INSERT INTO FOF VALUES(1, 1, 2, 10);
INSERT INTO FOF VALUES(2, 2, 3, 20);
INSERT INTO FOF VALUES(3, 3, 4, 30);
INSERT INTO FOF VALUES(4, 4, 5, 40);
commit;