-- https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/create-property-graph.html
CREATE OR REPLACE VIEW V1 AS
SELECT ID AS K, NAME, AGE, MANAGER FROM EMP
WHERE ID > 2;
CREATE PROPERTY GRAPH G
VERTEX TABLES(
  V1 AS E
    KEY(K)
    LABEL EMPLOYEE 
    PROPERTIES(K, NAME, AGE)
)
EDGE TABLES(
  V1 AS MANAGER KEY(K)
  SOURCE KEY(K) REFERENCES E(K)
  DESTINATION KEY(MANAGER) REFERENCES E(K)
  NO PROPERTIES
);