-- https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/create-property-graph.html
CREATE OR REPLACE VIEW V AS
SELECT EMP.ID, EMP.NAME, EMP.AGE, DPT.NAME AS DEPARTMENT,
MAX(EMP.AGE) OVER (PARTITION BY DPT.ID) AS MAX_AGE
FROM EMP,DPT
WHERE EMP.DEPARTMENT = DPT.ID;
CREATE PROPERTY GRAPH G
VERTEX TABLES(
V AS EMPLOYEE
KEY(ID)
LABEL EMPLOYEE
PROPERTIES(NAME, AGE, DEPARTMENT, MAX_AGE)
)
EDGE TABLES(
FOF AS friend_of KEY(ID)
SOURCE KEY(SRC) REFERENCES EMPLOYEE(ID)
DESTINATION KEY(DST) REFERENCES EMPLOYEE(ID)
PROPERTIES(E_COST)
);