-- https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/create-property-graph.html
CREATE OR REPLACE VIEW V1 AS SELECT * FROM F(EMP);
CREATE OR REPLACE VIEW V2 AS SELECT * FROM F(FOF);
CREATE PROPERTY GRAPH G
VERTEX TABLES(
V1 AS EMPLOYEE
KEY(ID)
LABEL EMPLOYEE
PROPERTIES ARE ALL COLUMNS
)
EDGE TABLES(
V2 AS friend_of KEY(ID)
SOURCE KEY(SRC) REFERENCES EMPLOYEE(ID)
DESTINATION KEY(DST) REFERENCES EMPLOYEE(ID)
PROPERTIES(E_COST)
);