-- https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/create-property-graph.html
CREATE OR REPLACE VIEW V1 AS
SELECT EMP.ID, EMP.NAME, EMP.AGE, DPT.NAME AS DEPARTMENT
FROM EMP,DPT
WHERE EMP.DEPARTMENT = DPT.ID;
CREATE PROPERTY GRAPH G1
VERTEX TABLES(
V1 AS EMPLOYEE
KEY(ID)
LABEL EMPLOYEE
PROPERTIES(ID, NAME, DEPARTMENT)
)
EDGE TABLES(
FOF AS friend_of KEY(ID)
SOURCE KEY(SRC) REFERENCES EMPLOYEE(ID)
DESTINATION KEY(DST) REFERENCES EMPLOYEE(ID)
LABEL friend_of
PROPERTIES(E_COST)
);