-- https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/create-property-graph.html
CREATE OR REPLACE VIEW V AS
SELECT DPT.ID, DPT.NAME, COUNT(EMP.ID) AS EMPLOYEES
FROM EMP,DPT
WHERE EMP.DEPARTMENT(+) = DPT.ID
GROUP BY DPT.ID, DPT.NAME;
CREATE PROPERTY GRAPH G
VERTEX TABLES(
EMP AS EMPLOYEE
KEY(ID)
LABEL EMPLOYEE
PROPERTIES ARE ALL COLUMNS,
V AS DEPARTMENT
KEY(ID)
LABEL DEPARTMENT
PROPERTIES ARE ALL COLUMNS
)
EDGE TABLES(
EMP AS employee_of KEY(ID)
SOURCE KEY(ID) REFERENCES EMPLOYEE(ID)
DESTINATION KEY(DEPARTMENT) REFERENCES DEPARTMENT(ID)
NO PROPERTIES
);