-- https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/create-property-graph.html
CREATE VIEW V3 AS
SELECT ROWNUM AS ID, CONNECT_BY_ROOT id AS emp, manager AS mgr,
SYS_CONNECT_BY_PATH(name, '/') AS path
FROM emp
WHERE manager IS NOT NULL
CONNECT BY PRIOR manager = id;
CREATE PROPERTY GRAPH G
VERTEX TABLES(
EMP AS EMPLOYEE
KEY(ID)
PROPERTIES(ID, NAME)
)
EDGE TABLES(
V3 AS MANAGER KEY(ID)
SOURCE KEY(EMP) REFERENCES EMPLOYEE(ID)
DESTINATION KEY(MGR) REFERENCES EMPLOYEE(ID)
PROPERTIES(PATH)
);