-- https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/DROP-PLUGGABLE-DATABASE.html
ALTER SESSION SET _ORACLE_SCRIPT"=true ;
ALTER PLUGGABLE DATABASE APP_ROOT_CLONE CLOSE;
DROP PLUGGABLE DATABASE APP_ROOT_CLONE FORCE INCLUDING DATAFILES;